openapi: 3.0.3
info:
  title: BTC Trade API - Positions
  version: 1.0.0
  description: Endpoint to list open investment positions with current buy snapshot.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Position:
      type: object
      required: [positionId, openedAt, qtyBTC, unitPriceBRL, investedBRL, currentPriceBRL, changePct, currentGrossBRL, priceTs]
      properties:
        positionId:
          type: string
          format: uuid
        openedAt:
          type: string
          format: date-time
        qtyBTC:
          type: number
        unitPriceBRL:
          type: number
        investedBRL:
          type: number
        currentPriceBRL:
          type: number
        changePct:
          type: number
          description: Relative change between current buy and unit price (4 decimals)
        currentGrossBRL:
          type: number
        priceTs:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      required: [code, message, requestId]
      properties:
        code:
          type: string
        message:
          type: string
        requestId:
          type: string
paths:
  /positions:
    get:
      summary: List open positions with single buy snapshot for PnL
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of positions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Position'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Position price unavailable (no quote and no cache)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

