openapi: 3.0.3
info:
  title: BTC Trade API - Quotes
  version: 1.0.0
  description: Endpoint to fetch current BTC quote (buy/sell) with Redis cache and provider fallback.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    QuoteResponse:
      type: object
      required: [buy, sell, source, ts, ageMs]
      properties:
        buy:
          type: number
          description: Current buy price (BRL)
        sell:
          type: number
          description: Current sell price (BRL)
        source:
          type: string
          example: MercadoBitcoin
        ts:
          type: string
          format: date-time
          description: ISO-8601 timestamp of the quote snapshot
        ageMs:
          type: number
          description: Milliseconds since ts at response time
    ErrorResponse:
      type: object
      required: [code, message, requestId]
      properties:
        code:
          type: string
        message:
          type: string
        requestId:
          type: string
paths:
  /quotes/current:
    get:
      summary: Get current BTC quote (buy/sell)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Quote provider unavailable and no cached value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

